apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-py.fullname" . }}
  labels:
    {{- include "hello-py.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-py.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-py.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-u", "/app/app.py"]
          env:
            - name: GREETING
              value: {{ .Values.greeting | quote }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: app
              mountPath: /app
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app
          configMap:
            name: {{ include "hello-py.fullname" . }}-app
