apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unsloth-work
  namespace: unsloth
  labels:
    app: unsloth-studio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
