apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lakefs
  labels:
    app: lakefs
spec:
  namespaceSelector:
    matchNames:
      - lakefs
  selector:
    matchLabels:
      app: lakefs
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
