apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentgateway-admin
  namespace: agentgateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: gateway.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentgateway
                port:
                  number: 15000
