apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  labels:
    app: minio
spec:
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      app: minio
  endpoints:
    - port: api
      path: /minio/v2/metrics/cluster
      interval: 30s
    - port: api
      path: /minio/v2/metrics/node
      interval: 30s
