apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-stable.yaml
  - service-canary.yaml
  - virtual-service.yaml
  - analysis-template.yaml
  - rollout.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: podinfo
    includeSelectors: false
