apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      releaseName: elasticsearch
      values: |
        replicas: 1
        minimumMasterNodes: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: true
        antiAffinity: "soft"
        esJavaOpts: "-Xmx1g -Xms1g"
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
