apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evidently
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/crossproducts/Notes
    targetRevision: main
    path: .labs/Local-Kubernetes/ml-pipeline/manifests/evidently
  destination:
    server: https://kubernetes.default.svc
    namespace: evidently
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
