apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target: { kind: HTTPRoute, name: kiali }
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: kiali.prod.127.0.0.1.sslip.io
