apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: label-studio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/crossproducts/Notes
    targetRevision: main
    path: .labs/Local-Kubernetes/mlops/manifests/label-studio
  destination:
    server: https://kubernetes.default.svc
    namespace: label-studio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
