apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target: { kind: Gateway, name: fable-gateway }
    patch: |
      - op: replace
        path: /spec/listeners/0/hostname
        value: "*.staging.127.0.0.1.sslip.io"
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.staging.127.0.0.1.sslip.io"
  - target: { kind: Certificate, name: fable-wildcard }
    patch: |
      - op: replace
        path: /spec/dnsNames
        value: ["*.staging.127.0.0.1.sslip.io"]
