apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-py.fullname" . }}
  labels:
    {{- include "hello-py.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "hello-py.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
